---
title: "lit"
output: pdf_document
---

# Lit:
Increasing Russia’s Labour market openness has been a policy goal since the establishment of the Federation (Clarke 2000). This goal has broad consensual support. On one hand the IMF, the World Bank, and the OECD all cite the importance of labour mobility and the impracticality of Soviet jobs guarantees. On the other, modern commentators in Russia including the former president cite the growing importance of even more labour market flexibility, not only in terms of jobs but also in terms of the regions where job searching takes place (Medvedev). 

The benefits of mobile labour markets, at least in the short term, are obvious to employers and managers. Granting them freedom to hire and fire workers easily allows them to adjust to changing labour demands quickly, which in turn allows them to limit their obligations to workers. The benefits of mobile labour markets for workers and their families are less obvious. On one hand, job-search theories predict that flexible markets stem from variance in wages and that mobility brings opportunity for improving these wages. Job mobility, in short, stems from a worker’s mismatch between reservation wage x (the minimal earnings needed to move from unemployment to employment) and reservation wage y (the minimal earnings needed to move employers from a given position to a new position). Thus, increased rates of voluntary mobility (quits and promotions) are a positive sign, one that suggests workers “move up” in the market. In a similar vein, job-matching theories claim mobility between positions is the best way to secure occupational attainment. Dissatisfaction with work, pay, and conditions can be corrected by simply quitting for a better job or pursuing a promotion, vacating the position for someone who is willing to fill the previous job. Here too rates of voluntary quits and promotions stem from varied conditions in a labour market, and an emphasis on individualised job matching, where workers are responsible for finding the best job for their role. 

Despite the theories above, research suggests that mobility premiums in pay (job-searching) and conditions (job matching) are not always evident, especially when researching quits alone. 

Paradoxically, the IMF et al (1991, p143) describe the Soviet labour market as extremely mobile with high levels of turnover, on par with many European countries, and surpassing countries like France and Japan. Such levels of turnover existed in a system with little variance in wages, and less variance in working conditions. At the same time, writers describe Russia’s current labour market as immobile, despite significant variance in wages and working conditions between and within firms. 
